DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 4
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  # TRANSFORMS: ["random_resized_crop", "horizontal_flip", "normalize"]
  TRANSFORMS: ["random_resized_crop", "normalize"]

#["random_resized_crop", "horizontal_flip", "random_rotation", "normalize"]  ["random_resized_crop", "normalize"]"colorjitter", 
OPTIM:
  NAME: "adamw" #adamw
  LR: 0.0025
  MAX_EPOCH: 100
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"
  # INIT_WEIGHTS: '/home/diaoyueqin/dyq/BiomedCoOp/output/btmri/shots_128/BiomedCoOp_BiomedCLIP/nctx4_cscFalse_ctpend/seed42/prompt_learner/model.pth.tar-100'

TRAINER:
  BIOMEDCOOP:
    CTX_INIT: "a MR image of a" #"a MR image of a"
    ATT_INIT: "position shape boundary signal" #enhancement "position shape boundary signal"
    SCCM_LAMBDA: 2.5 #0.5
    KDSP_LAMBDA: 2.5 #0.25
    TAU: 1.5
    N_PROMPTS: 30
    N_CTX: 4
    CLASS_TOKEN_POSITION: "end"
    PREC: "fp32"
    
    # Attribute learning parameters
    ATTR_LEARNING: False
    ATTR_LAMBDA: 0.5
    ATTR_DIM: 64
    ATTR_TEMP: 0.07
    ATTR_MARGIN: 0.2
    N_ATT: 4
    # ATT1_TEXT: "shape"
    # ATT2_TEXT: "color"
    # ATT3_TEXT: "material"
    # ATT4_TEXT: "function"
    # ATT5_TEXT: "texture"
    ATT1_TEXT: "position"
    ATT2_TEXT: "shape"
    ATT3_TEXT: "boundary"
    ATT4_TEXT: "signal"
    ATT5_TEXT: "enhancement"
#     - 位置：Position
# - 形态：Shape
# - 边界：Boundary
# - 信号：Signal
# - 强化：Enhancement 